[package]
name = "wdf-kmdf-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.65.1"
cc = "1.0.79"
thiserror = "1.0.40"
winreg = "0.50.0"
